version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data



  pipeline:
    build: .
    container_name: pipeline_container
    depends_on:
      - postgres

volumes:
  postgres_data:
